// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gomail "gopkg.in/gomail.v2"

	mock "github.com/stretchr/testify/mock"
)

// IDialer is an autogenerated mock type for the IDialer type
type IDialer struct {
	mock.Mock
}

// DialAndSend provides a mock function with given fields: _a0
func (_m *IDialer) DialAndSend(_a0 ...*gomail.Message) error {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...*gomail.Message) error); ok {
		r0 = rf(_a0...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
