// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Listener is an autogenerated mock type for the Listener type
type Listener struct {
	mock.Mock
}

// GetId provides a mock function with given fields:
func (_m *Listener) GetId() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Handle provides a mock function with given fields: _a0
func (_m *Listener) Handle(_a0 interface{}) {
	_m.Called(_a0)
}

// SetId provides a mock function with given fields: _a0
func (_m *Listener) SetId(_a0 int) {
	_m.Called(_a0)
}
